name: build-ppp-executor
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read 

jobs:
  build:
    uses: ./.github/workflows/build-ecs.yml
    with:
      service_name: ppp-executor
